/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnotherPageRouteImport } from './routes/anotherPage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesCreateRouteImport } from './routes/quizzes/create'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes/$quizId'
import { Route as QuizzesQuizIdEditRouteImport } from './routes/quizzes/$quizId/edit'
import { Route as SessionsCodePlayRouteImport } from './routes/sessions/$code/play'
import { Route as SessionsCodeHostRouteImport } from './routes/sessions/$code/host'
import { Route as SignInRouteImport } from './routes/sign-in'

const AnotherPageRoute = AnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesCreateRoute = QuizzesCreateRouteImport.update({
  id: '/quizzes/create',
  path: '/quizzes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdEditRoute = QuizzesQuizIdEditRouteImport.update({
  id: '/quizzes/$quizId/edit',
  path: '/quizzes/$quizId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsCodePlayRoute = SessionsCodePlayRouteImport.update({
  id: '/sessions/$code/play',
  path: '/sessions/$code/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsCodeHostRoute = SessionsCodeHostRouteImport.update({
  id: '/sessions/$code/host',
  path: '/sessions/$code/host',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/sessions/$code/host': typeof SessionsCodeHostRoute
  '/sessions/$code/play': typeof SessionsCodePlayRoute
  '/sign-in': typeof SignInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/sessions/$code/host': typeof SessionsCodeHostRoute
  '/sessions/$code/play': typeof SessionsCodePlayRoute
  '/sign-in': typeof SignInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotherPage': typeof AnotherPageRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/$quizId/edit': typeof QuizzesQuizIdEditRoute
  '/quizzes/create': typeof QuizzesCreateRoute
  '/sessions/$code/host': typeof SessionsCodeHostRoute
  '/sessions/$code/play': typeof SessionsCodePlayRoute
  '/sign-in': typeof SignInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotherPage'
    | '/quizzes/$quizId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/create'
    | '/sessions/$code/host'
    | '/sessions/$code/play'
    | '/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotherPage'
    | '/quizzes/$quizId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/create'
    | '/sessions/$code/host'
    | '/sessions/$code/play'
    | '/sign-in'
  id:
    | '__root__'
    | '/'
    | '/anotherPage'
    | '/quizzes/$quizId'
    | '/quizzes/$quizId/edit'
    | '/quizzes/create'
    | '/sessions/$code/host'
    | '/sessions/$code/play'
    | '/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherPageRoute: typeof AnotherPageRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  QuizzesQuizIdEditRoute: typeof QuizzesQuizIdEditRoute
  QuizzesCreateRoute: typeof QuizzesCreateRoute
  SessionsCodeHostRoute: typeof SessionsCodeHostRoute
  SessionsCodePlayRoute: typeof SessionsCodePlayRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anotherPage': {
      id: '/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof AnotherPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/create': {
      id: '/quizzes/create'
      path: '/quizzes/create'
      fullPath: '/quizzes/create'
      preLoaderRoute: typeof QuizzesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId/edit': {
      id: '/quizzes/$quizId/edit'
      path: '/quizzes/$quizId/edit'
      fullPath: '/quizzes/$quizId/edit'
      preLoaderRoute: typeof QuizzesQuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$code/play': {
      id: '/sessions/$code/play'
      path: '/sessions/$code/play'
      fullPath: '/sessions/$code/play'
      preLoaderRoute: typeof SessionsCodePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$code/host': {
      id: '/sessions/$code/host'
      path: '/sessions/$code/host'
      fullPath: '/sessions/$code/host'
      preLoaderRoute: typeof SessionsCodeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherPageRoute: AnotherPageRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  QuizzesQuizIdEditRoute: QuizzesQuizIdEditRoute,
  QuizzesCreateRoute: QuizzesCreateRoute,
  SessionsCodeHostRoute: SessionsCodeHostRoute,
  SessionsCodePlayRoute: SessionsCodePlayRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
